networks:
  proxy-net:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=pipoca453
    networks:
      - proxy-net

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:pipoca453@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - proxy-net